
package Vista;

import Controlador.Controlador;

import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JTextArea;

/**
 *
 * @author juanx
 */
public class Ventana extends javax.swing.JFrame {

    /** Creates new form Ventana */
    public Ventana() {
        initComponents();
        this.setVisible(true);
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(1);
        this.botonEmpezar.setActionCommand(Controlador.COMENZAR);
        this.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent evt)
            {
                Controlador.terminar();
                
            }
        });
        System.out.println("Se creo la ventana");

    }
    
    public void addActionListener(ActionListener al)
    {
        this.botonEmpezar.addActionListener(al);
    }
    public String sentencias()
    {
        return this.textSentencias.getText();
    }
    public void mostrarConsulta(String s)
    {
        this.textResultados.setText(s);
    }
    public void mostrarError(String s)
    {
        this.textErrores.setText(s);
    }

    public JTextArea getTextErrores()
    {
        return textErrores;
    }

    public JTextArea getTextResultados()
    {
        return textResultados;
    }

    public JTextArea getTextSentencias()
    {
        return textSentencias;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        panelPrincipal = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSentencias = new javax.swing.JTextArea();
        panelDer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textResultados = new javax.swing.JTextArea();
        labelErrores = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textErrores = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        botonEmpezar = new javax.swing.JButton();

        panelPrincipal.setLayout(new java.awt.GridLayout(1, 0));

        panelIzq.setLayout(new java.awt.BorderLayout());

        textSentencias.setColumns(20);
        textSentencias.setRows(5);
        jScrollPane1.setViewportView(textSentencias);

        panelIzq.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelIzq);

        panelDer.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setText("Resultados");
        jPanel2.add(jLabel1);

        textResultados.setColumns(20);
        textResultados.setRows(5);
        jScrollPane2.setViewportView(textResultados);

        jPanel2.add(jScrollPane2);

        labelErrores.setText("Errores");
        jPanel2.add(labelErrores);

        textErrores.setColumns(20);
        textErrores.setRows(5);
        jScrollPane3.setViewportView(textErrores);

        jPanel2.add(jScrollPane3);

        panelDer.add(jPanel2);

        botonEmpezar.setText("Comenzar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEmpezar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(botonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelDer.add(jPanel1);

        panelPrincipal.add(panelDer);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelErrores;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea textErrores;
    private javax.swing.JTextArea textResultados;
    private javax.swing.JTextArea textSentencias;
    // End of variables declaration//GEN-END:variables

}
